import os

BOT_TOKEN = os.getenv("BOT_TOKEN", "your-bot-token")
WEBHOOK_URL = os.getenv("WEBHOOK_URL", "https://your-app-url.onrender.com/webhook")
NEON_DB_DSN = os.getenv("NEON_DB_DSN", "postgresql://USER:PASSWORD@HOST:PORT/DBNAME")
GROUP_IDS = [int(x) for x in os.getenv("GROUP_IDS", "-1001234567890").split(",")]  # 支持多个群
