services:
  - type: web
    name: telegram-scheduler-bot
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port 10000"
    envVars:
      - key: BOT_TOKEN
        fromSecret: BOT_TOKEN
      - key: WEBHOOK_URL
        value: "https://your-render-domain.onrender.com/webhook"
    autoDeploy: true
    # Render默认公开端口是10000
    ports:
      - port: 10000